### ISSUE TITLE
Multiple anchors targeting a single Modal

### ISSUE THREAD

**Issue by slavajacobson** [joaopereirawd/animatedModal.js#11]
Doesn't seem to be possible. Only one of the anchors would work.

**Comment by marcusvmsa** [comment]
I've tried here, two links anchoring to one model. Worked for me... What happen to you? Modal didn't open?

**Comment by joelnz** [comment]
Works if you use class on the link rather than id.

**Comment by Ash110** [comment]
@joelnz You, Sir, are a genius! Thank you!

**Comment by imtechnology** [comment]
I am having this issue as well but can not get this to work. Any help much appreciated.

The following combinations do not work and I am becoming desperate!

`<a id="demo01" href="#animatedModal">DEMO01</a>`
`<a id="demo01" href="#animatedModal">DEMO01</a>`

`<a class="demo01" href="#animatedModal">DEMO01</a>`
`<a class="demo01" href="#animatedModal">DEMO01</a>`

`<a id="demo01" class="demo01" href="#animatedModal">DEMO01</a>`
`<a id="demo01" class="demo01" href="#animatedModal">DEMO01</a>`

`$("#demo01").animatedModal();`

**Comment by artpenteur** [comment]
Hello!
try this...

a class="demo01" href="#animatedModal">DEMO01</a>
a class="demo01" href="#animatedModal">DEMO01</a>

a class="demo01" href="#animatedModal">DEMO01</a>
a class="demo01" href="#animatedModal">DEMO01</a>

a class="demo01" class="demo01" href="#animatedModal">DEMO01</a>
a class="demo01" class="demo01" href="#animatedModal">DEMO01</a>

$(".demo01").animatedModal();

**Comment by joaopereirawd** [comment]
@artpenteur isn't possible to have Multiple ID'S with the same name! 

Try use only classes, this shoud be work fine!


```
<a class="demo01" href="#animatedModal">DEMO01</a>
<a class="demo01" href="#animatedModal">DEMO01</a>

<a class="demo01" href="#animatedModal">DEMO01</a>
<a class="demo01" href="#animatedModal">DEMO01</a>

<a class="demo01" class="demo01" href="#animatedModal">DEMO01</a>
<a class="demo01" class="demo01" href="#animatedModal">DEMO01</a> 
```

`$(".demo01").animatedModal();`
