### ISSUE TITLE
Can we get this on Bower?

### ISSUE THREAD

**Issue by natecox** [joaopereirawd/animatedModal.js#13]
I like your concept a lot, but would really like to be able to get this through Bower rather than downloading and including in my repo directly.

Can you get this up on Bower for us?

Note: I see that you already have a `bower.json` ready, but it doesn't seem to actually exist in bower.

**Comment by GesJeremie** [comment]
+1, you forgot to publish it on bower ;)

**Comment by pedroadame** [comment]
+1!

**Comment by panoply** [comment]
+1 Bower up son!

**Comment by alexandrevilain** [comment]
You can do : 

`bower install https://github.com/joaopereirawd/animatedModal.js.git`

**Comment by GesJeremie** [comment]
@alexandrevilain This is sad and you know it

**Comment by natecox** [comment]
So.. is this a wont-fix situation?

**Comment by waveminded** [comment]
Yeah, no doubt... Bower please +1
