### ISSUE TITLE
Not working locally for me

### ISSUE THREAD

**Issue by simsketch** [joaopereirawd/animatedModal.js#2]
Not sure what the problem is...will keep you posted.  Looks great otherwise! Thanks!

**Comment by joaopereirawd** [comment]
Hi simsketch,

Which  browser are you using ? and version ?
Make sure that your browser is up to date and has support for CSS3 Transitions. 

Try to download the master branch and follow the demos

https://github.com/joaopereirawd/animatedModal.js/archive/master.zip

**Comment by leshek-pawlak** [comment]
I'm using Chromium 41, and I have the same problem like @simsketch.
Sorry, demo included to repo is not working.

**Comment by joaopereirawd** [comment]
Hi Lesyek, 
Thanks for your feedback. 

I get jquery library by google servers, maybe you need simulate a apache server to run a jQuery by google. (ex: XAMPP)

But don't you worry, this problem is solved. Try to download the demo now. 

Cheers.

**Comment by leshek-pawlak** [comment]
Great! Now it works fine. Thanks!

**Comment by joaopereirawd** [comment]
:+1:
