### ISSUE TITLE
open animatedModal after ajax request

### ISSUE THREAD

**Issue by morteza-gho** [joaopereirawd/animatedModal.js#29]
Hi, how to open animatedModal after ajax request?

**Comment by arifhussain353** [comment]
waiting for same issue response

**Comment by khiconit** [comment]
Me too

**Comment by sameerpallav** [comment]
its easy... modify modal.click handler to modal.on('open', function(){...})
then use $(selector).trigger('open') in your ajax success.

**Comment by parvez301** [comment]
in success function trigger the click event manually.  
eg `success : function(response){
$("#your-id-name").trigger('click');
}`
