### ISSUE TITLE
Proposal: Remove the background-color-property

### ISSUE THREAD

**Issue by flash1293** [joaopereirawd/animatedModal.js#5]
Wouldn't it be much easier to let the user set the background-color of his/her modal via css?

Talking about separation of concerns, IMHO the background-color of the modal is not a question of functionality (js), but a question of presentation (css).

**Comment by rafic20** [comment]
Seconded. It seems more natural to allow users to change background colour (or image, or whatever) using CSS.

**Comment by joaopereirawd** [comment]
Yes, i understand your point of view. 
You can ignore js option and choose override the background-color with css.
