### ISSUE TITLE
don't use href

### ISSUE THREAD

**Issue by gerswin** [joaopereirawd/animatedModal.js#8]
don't use hfref because don't work with some js router frameworks

**Comment by bjornweb** [comment]
Why is this closed?
I did not find any reason why this is mandatory?

Using `href` also causes a range of compatibility issues.
Currently working with a theme that has anchor scroll functions which run when I want to open a modal.

I had to modify your script to use `data()`.
Now I can simply use the following for creating buttons:
```html
<div id='modal_{$id}' class='modal_button' data-modaltarget='aModal_{$id}'>button</div>
```
